# Generated by Django 3.0.11 on 2021-01-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210119_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='members.Community'),
        ),
    ]
