# Generated by Django 3.0.11 on 2021-01-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210119_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityattributes',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='members.Community'),
        ),
        migrations.AlterField(
            model_name='communityattributes',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='members.Meta'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='members.Community'),
        ),
    ]
