# Generated by Django 3.0.11 on 2021-01-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210120_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='Metadata',
        ),
    ]
