# Generated by Django 3.0.11 on 2021-01-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210120_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityattributes',
            name='type',
            field=models.ForeignKey(limit_choices_to={'type': 'community_attributes'}, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='members.Metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('membership_level', 'Membership Level'), ('community_attributes', 'Community Attribute'), ('other', 'Other')], max_length=64),
        ),
    ]
