# Generated by Django 3.0.11 on 2021-01-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210120_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
