# Generated by Django 3.0.11 on 2021-01-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_membership_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(default='NoName', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=False, help_text="If 'True' Community will integrate with Webex Teams and Cisco Mailer"),
        ),
        migrations.AddField(
            model_name='community',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="If 'True' Community will be displayed on tool's main page"),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, help_text="Member's coverage country", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.CharField(blank=True, help_text="Member's coverage region", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, help_text="Member's actual role at Cisco", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='theater',
            field=models.CharField(blank=True, help_text="Member's coverage theater", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='abreviation',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('type', 'value')},
        ),
    ]
