# Generated by Django 3.0.11 on 2021-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20210122_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityattributes',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
